# fly.toml app configuration file generated for tailwings-cool-dew-3582 on 2025-05-02T07:55:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tailwings-cool-dew-3582'
primary_region = 'ord'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]

[env]
  PORT = '41641'

[http_service]
  internal_port = 41641
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'udp'
  internal_port = 41641
  processes = ['app']

  [[services.ports]]
    port = 41641

  [services.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 75

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
